### ISSUE TITLE
Failure shown when signing in with GitHub

### ISSUE THREAD

**Issue by steveafrost** [thebrianemory/flatcasts#2]
When trying to sign into GitHub to view casts, I receive the following error:

```
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.
```

The URL I end up at when seeing this message is http://www.flatcasts.com/auth/failure?message=redirect_uri_mismatch&strategy=github.

**Comment by thebrianemory** [comment]
Hi Steve,

Are you still having trouble with this? If so, can you give some more details about the steps that led you to that error? Things like what browser you are using, the order of things you clicked on, etc.

Thanks,

Brian

**Comment by steveafrost** [comment]
Yeah, I'm still experiencing this issue. I can replicate on Mac & Windows on Chrome and Firefox. I have tried in incognito to see if some junk cache/cookies were causing it but I still receive the error.

To reproduce
1. Visit flatcasts.herokuapp.com/#/
2. Click on Sign In With GitHub  (or the You must be signed in button)
3. Observe error that looks [like this](https://cl.ly/393A0N0M0n3i)

Troubleshooting
- Tried to clear cookies & cache
- Tried in incognito on Chrome and private browsing mode on FF

**Comment by thebrianemory** [comment]
Try visiting http://www.flatcasts.com instead of http://flatcasts.herokuapp.com and let me know if that works for you. The GitHub oath is expecting http://www.flatcasts.com and I think that's the issue you're seeing. I was able to duplicate your error by visiting http://flatcasts.herokuapp.com.

**Comment by steveafrost** [comment]
Oh yup, that works. Thanks Brian. I must have had the old URL from when you shared it early on.
